matrix:
  include:
    - os: linux
      sudo: required
      language: ruby
      services:
        - docker
    - os: osx
      language: ruby

cache: bundler

install:
  - bundle install

script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      VERBOSE=1 bundle exec rspec -t ~docker
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
      VERBOSE=1 bundle exec rspec
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
      MEDUSA="$PWD/bin/medusa"

      cd spec/share/roles/docker-masquerade

      $MEDUSA ansible-playbook ./playbook.yml
    fi