matrix:
  include:
    - os: linux
      sudo: required
      language: ruby
      services:
        - docker
    - os: osx
      language: ruby

cache: bundler

install:
  - bundle install

script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      VERBOSE=1 bundle exec rspec -t ~docker
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
      VERBOSE=1 bundle exec rspec
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
      ANSIBLE_CONFIG=./ci/ansible.cfg ./bin/medusa ansible-playbook ./ci/playbook.yml
    fi